![CLASS](https://raw.githubusercontent.com/MlvPrasadOfficial/ref//main/npclass.png)

In [2]:

# #NUMPY CLASS - STARTS AT 5.35 PM


In [ ]:
1
1 2 
1 2 3
1 2 3 4
1 2 3 4 5

In [22]:
for i in range(5):                  # 0 1 2 3 4
    for j in range(i+1) : # 5 5 5 5 5 # 1 2 3 4 5
        print(j+1,end= " ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
****
***
**
*

In [14]:
for i in range(4): # 4-0 4-1 4-2 4-3
    for j in range(4-i):  # 4 3 2 1
        print("*",end="")
    print()

****
***
**
*


# ****
 ***
  **
   *

In [3]:
for i in range(5): # 0 1 2 3 4
    for j in range(10,15): # 10 11 12 13 14
        print(i,j)

0 10
0 11
0 12
0 13
0 14
1 10
1 11
1 12
1 13
1 14
2 10
2 11
2 12
2 13
2 14
3 10
3 11
3 12
3 13
3 14
4 10
4 11
4 12
4 13
4 14


In [23]:
import numpy as np

a = np.array([1,2,3])
print(a)


[1 2 3]


!pip install numpy

In [33]:
ss = np.zeros((3,3))
ss

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
ww = np.ones((3,3))

ww

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
summ = ss + ww
summ

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
zz = np.array([1,2,3])
yy = np.array([4,5,6])
xx = yy + zz
xx

array([5, 7, 9])

In [40]:
cc = zz **  yy
cc

array([  1,  32, 729])

In [42]:
a= np.zeros([3,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
g = a.flatten()
g

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
f = g.reshape([3,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
j = np.array([1,2,3])
print(np.mean(j),np.median(j),np.std(j),np.min(j),np.max(j))

2.0 2.0 0.816496580927726 1 3


In [52]:
rand = np.random.rand()
rand

0.9030169305111088

In [53]:
rand1 = np.random.rand(4,3)
rand1

array([[0.24687203, 0.93195848, 0.47676583],
       [0.49539871, 0.51649074, 0.98945853],
       [0.44891814, 0.74465532, 0.99845786],
       [0.68676756, 0.85131343, 0.17402525]])

In [56]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

res = np.matmul(a,b)
res


array([[19, 22],
       [43, 50]])

In [57]:
d = np.array([2,2,3,3,4,4,5,5])
d = np.unique(d)
d

array([2, 3, 4, 5])

In [ ]:
# np.sin . np.cos np.tan np.sqrt np.exp

In [62]:
a = np.array([1,2,3])
b = np.array([10,11,12])
c = np.array([20,22])

d = np.concatenate((a,b,c))
d

array([ 1,  2,  3, 10, 11, 12, 20, 22])

In [63]:
a = np.array([15,22,16])
a = np.sort(a)
a

array([15, 16, 22])

In [65]:
a = np.array([1,2,3])
b = np.array([10,11,12])
c = np.dot(a,b)
c

68

In [66]:
a = np.array([10,20,30,40,50])
b = np.array([20,30,10,10,10])

ans = a == b
ans

array([False, False,  True,  True,  True])

In [67]:
a = np.array([10,20,30,40,50])

maxi = np.max(a)
maxi

50

In [68]:
a = np.array([10,20,30,40,50])

max2 = np.argmax(a)
max2

4

In [72]:
a = np.array([10,20,30,40,50])
main = a[(a>25) & (a< 45)]
main

array([30, 40])

In [73]:
a = np.array([1,1,1,2,2,2,23,3,34,4,4])
uni, coun = np.unique(a,return_counts = True)
print(uni)
print(coun)

[ 1  2  3  4 23 34]
[3 3 1 2 1 1]


In [74]:
a = np.array([1,1,1,-2,2,2,23,-3,34,4,4])
c = np.abs(a)
c

array([ 1,  1,  1,  2,  2,  2, 23,  3, 34,  4,  4])

In [76]:
a= np.array([10,12,23])
b = np.cumsum(a)
b

array([10, 22, 45])

In [77]:
a= np.array([10,12,23])
b = np.cumprod(a)
b

array([  10,  120, 2760])

In [79]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.transpose(a)
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [80]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = a.T
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [81]:
a = np.array([[1,2.8,3],
              [4,9.77,6],
              [7,8,9]])

b = np.round(a)
b

array([[ 1.,  3.,  3.],
       [ 4., 10.,  6.],
       [ 7.,  8.,  9.]])

In [85]:
# range 
# arrange
a = list(range(6))
print(a)
c = np.arange(6)
print(c)
P



[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [87]:
a = np.array([1,2,3])
b = np.power(a,3)
print(b)

[ 1  8 27]


In [92]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

ans = np.stack((a,b,c) ,axis= 0)
ans

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

ans1 = np.stack((a,b,c) ,axis= 1)
ans1

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [96]:
a = np.random.randint(45,60,(3,3))
a

array([[45, 59, 51],
       [47, 55, 59],
       [54, 49, 48]])

In [97]:
f = np.arange(10,40,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [106]:
g= np.linspace(500,600,10)
g

array([500.        , 511.11111111, 522.22222222, 533.33333333,
       544.44444444, 555.55555556, 566.66666667, 577.77777778,
       588.88888889, 600.        ])

In [107]:
#hstacka = 
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.hstack((a,b))
c



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [108]:
#hstacka = 
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.vstack((a,b))
c


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])